### ISSUE TITLE
Storing prefixes for the servers.

### ISSUE THREAD

**Issue by rchomczyk** [Kaktushose/jda-commands#1]
I think there should be option too choose a option where we want to store our data, like mysql, moongose, sqlite, yaml, json etc.

**Comment by Kaktushose** [comment]
Imo storing guild prefixes and other settings is something the bot developer should generally take care of and not the command framework itself. For constant values you can use the `settings.yaml` file https://github.com/Kaktushose/jda-commands/wiki/Config-File
However we are currently working on an implementation of redis and I'll also consider to offer more options for storing data.

**Comment by oleggtro** [comment]
Working on it... I've completed the redis integration, will test it this afternoon and create a pr in the next few days...

**Comment by oleggtro** [comment]
I actually have code at https://github.com/cloudybyte/jda-commands [dev branch] but I am unable to test it because of some weird behaviour...
