### ISSUE TITLE
[BUG] Reply message always ephemeral

### ISSUE THREAD

**Issue by stijnb1234** [Kaktushose/jda-commands#115]
Related version: 4.0.0-alpha.1

The reply message is always ephemeral, even when it's not set (default false).

![image](https://user-images.githubusercontent.com/27051051/234950317-2f7a2fb7-ff7f-481a-8697-235d21477ff9.png)

![image](https://user-images.githubusercontent.com/27051051/234950384-f594ab90-98a9-4c62-a7d0-da8937e68998.png)

**Comment by Kaktushose** [comment]
The ephemeral field had a true default value in the `@Interaction` annotation, temp workaround would be to explicitly set it to false. 

Fixed with [c881798](https://github.com/Kaktushose/jda-commands/commit/c8817987c7625d58dc4aa8b9bede6d05692c8f0c), will be deployed with 4.0.0-alpha.2
