### ISSUE TITLE
[FEATURE] Handle unknown interactions

### ISSUE THREAD

**Issue by Kaktushose** [Kaktushose/jda-commands#120]
# Problem
The framework needs to handle incoming unknown interactions correctly. I can think of 2 scenarios at the moment. 1. the framework is in an invalid state and the interactions registered with discord do not match those of the framework. This should not happen and is always an exception, since we update the command state at every framework start. 2. an interaction was deliberately unregistered, this should mainly affect components. 

# Current situation
a) The CommandHandler throws an IllegalStateException. 
b) The ButtonHandler just sends an ephemeral message stating that the interaction timed out. 

Situation a) can be customized by using the `getCommandExecutionFailedMessage` method, thus I don't think we need to change anything here. However situation b) needs to be handled. 

# Solution
The simplest approach would be to add a `getUnknownInteractionMessage` method to the ErrorFactory. This would be a universal solution for buttons and all upcoming component implementations. In situation a) this message should not be used, because it always represents an unexpected error that should throw, as stated above.

**Comment by stijnb1234** [comment]
+1, got this situation too (IllegalStateException)

**Comment by Kaktushose** [comment]
honestly this should not happen. Can you give more details?
