### ISSUE TITLE
Add support for command groups & Modals

### ISSUE THREAD

**Issue by Scyye** [Kaktushose/jda-commands#121]
Adding support for command groups & subcommands would be insanely useful.
As well as support for modals.

**Comment by Kaktushose** [comment]
Subcommands und groups are already supported and support for modals is planned

**Comment by Kaktushose** [comment]
Back at my PC, let's give you a quick example of how to use command groups:

```java
@Interaction
public class CommandGroupExample {

    @SlashCommand(value = "mod report create")
    public void onReportCreate(CommandEvent event, Member target) {
        event.reply("report created");
    }

    @SlashCommand(value = "mod report list")
    public void onReportList(CommandEvent event) {
        event.reply("list of reports");
    }

    @SlashCommand(value = "mod ban")
    public void onBan(CommandEvent event, Member target) {
        event.reply("member banned");
    }
}
```
based on the command names jda-commands generated the following command tree:

```
└── mod
    ├── ban
    └── report
        ├── list
        └── create
```
which results in the registration of the following commands: `mod ban, mod report list, mod report create`

**Comment by Scyye** [comment]
oh so you just add spaces?

noted, thank you!

**Comment by Kaktushose** [comment]
> oh so you just add spaces?

yeah exactly, it's straight forward
