### ISSUE TITLE
[QUESTION] How do I make commandautocompleteevent work?

### ISSUE THREAD

**Issue by Scyye** [Kaktushose/jda-commands#125]
@Choices({"choice 1", "choice 2", "etc."}) is an annotation, and because of that, you have to statically type all the params, rather than this, is there a way to make a commandautocompleteevent work properly?

**Comment by Kaktushose** [comment]
> is there a way to make a commandautocompleteevent work properly?

Currently no, but there will be a way in the future. Choices have already been implemented because they are part of the command definition, but autocomplete events are a separate element. 

Currently I don't have any time to code, but autocomplete will be added within the next release(s).  

Closing this issue since this feature is already part of my internal roadmap

**Comment by Kaktushose** [comment]
implemented with [4.0.0-alpha.4](https://github.com/Kaktushose/jda-commands/releases/tag/v4.0.0-alpha.4)

**Comment by Scyye** [comment]
![image](https://github.com/Kaktushose/jda-commands/assets/97131358/8278e4ab-5c2e-4a59-b080-13be94cb1aa7)
![image](https://github.com/Kaktushose/jda-commands/assets/97131358/b38c044d-57a7-477f-9e71-2f825c6a0adc)

am i doin somethin wrong?

**Comment by Kaktushose** [comment]
you need to specify the command name and not the parameter name. for you exmaple this would be `package list search`

**Comment by Scyye** [comment]
so would i need to do separate things for each of the commands that all have a `community` param?;

**Comment by Kaktushose** [comment]
You can specify multiple commands per AutoComplete, but yes

**Comment by Scyye** [comment]
could you give an example?

**Comment by Kaktushose** [comment]
```java
@Interaction
public class AutoCompleteTest {

    private final String[] words = new String[]{"apple", "apricot", "banana", "cherry", "coconut", "cranberry"};

    @SlashCommand("fruit")
    public void onFruitCommand(CommandEvent event, @Param("fruit to find") String name) {
        event.reply("You selected %s", name);
    }

    @SlashCommand("food")
    public void onFoodCommand(CommandEvent event, @Param("fruit to find") String name) {
        event.reply("You selected %s", name);
    }

    @AutoComplete({"fruit", "food"})
    public void onAutoComplete(AutoCompleteEvent event) {
        event.replyChoices(Stream.of(words)
                .filter(word -> word.startsWith(event.getValue()))
                .map(word -> new Command.Choice(word, word))
                .collect(Collectors.toList())
        );
    }
}
```

Also be aware of the `AutoCompleteEvent#getName()` method to retrieve the name of the parameter, in case you have more than one parameter per command.

**Comment by Scyye** [comment]
this following code doesnt seem to be workin?
```java
@AutoComplete(value = {"package search", "package author", "package info"})
public void onAutocompleteCommunity(AutoCompleteEvent event) {
    if (event.getName().equals("community"))
        event.replyChoices(Stream.of(Bot.bot.tsja.getCommunities())
            .filter(community -> community.getIdentifier().startsWith(event.getValue()))
            .map(community -> new Command.Choice(community.getIdentifier(), community.getIdentifier()))
            .collect(Collectors.toList())
    );
}
```

any clue?

**Comment by Kaktushose** [comment]
I've used the following code to test your use case on my machine and it worked fine:

```java
@Interaction
public class AutoCompleteTest {

    private final String[] words = new String[]{"apple", "apricot", "banana", "cherry", "coconut", "cranberry"};

    @SlashCommand(value = "package search")
    public void onCommand1(CommandEvent event, String community) {
        event.reply("You selected %s", community);
    }

    @SlashCommand(value = "package author")
    public void onCommand2(CommandEvent event, String community) {
        event.reply("You selected %s", community);
    }

    @SlashCommand(value = "package info")
    public void onCommand3(CommandEvent event, String community) {
        event.reply("You selected %s", community);
    }

    @AutoComplete(value = {"package search", "package author", "package info"})
    public void onAutoComplete(AutoCompleteEvent event) {
        if (event.getName().equals("community")) {
            event.replyChoiceStrings(Stream.of(words)
                    .filter(word -> word.startsWith(event.getValue()))
                    .collect(Collectors.toList())
            );
        }
    }
}
```

Please provide your debug log file and also double check that the error is not caused by your `getCommunities` method, because i have no influence on your bot code

**Comment by Kaktushose** [comment]
While working on a feature that allows to only use the top level name, in this case "package" to register all sub commands I've encountered a bug, which sometimes leads to autocomplete not being registered correctly. This got fixed with commit adbdc4190ee87549677303869868acebb2887d18 and will be shipped with the next release. 

Here is the maven snippet to use this commit as long as the release isn't ready:
```xml
<dependency>
    <groupId>com.github.Kaktushose</groupId>
    <artifactId>jda-commands</artifactId>
    <version>adbdc4190e</version>
</dependency>
```

please let me know if this fixes your issue

**Comment by Scyye** [comment]
that version doesnt work. 
![image](https://github.com/Kaktushose/jda-commands/assets/97131358/687b53d4-6276-4c21-8721-d31bd65957a3)

**Comment by Scyye** [comment]
using that version seems to disable the commands?
but also not?

![image](https://github.com/Kaktushose/jda-commands/assets/97131358/dfe7badc-9301-4254-9e6e-649a83493535)
(its not the apple profile picture, and its in the server)

but then,
![image](https://github.com/Kaktushose/jda-commands/assets/97131358/44ad49b8-d8e1-4c1e-b058-333dc5e6c76f)
with this at the end of my start
```java
Bot.bot.jda.retrieveCommands().queue(commands -> {
    commands.forEach(command -> {
        System.out.println(command.getName());
    });
});
```

**Comment by Kaktushose** [comment]
will be fixed with the next commit

**Comment by Kaktushose** [comment]
0199890b7f71603050c80fdd344673d531cd700a should fix this

**Comment by Scyye** [comment]
Confirmed to be working, thank you!
