### ISSUE TITLE
Where to find "log console"

### ISSUE THREAD

**Issue by JoshCantCode** [Kaktushose/jda-commands#136]
Been looking around in my project + the issues here and ive seen something about logback. Is there a way i can have the stacktrace sent in the console too, as i would rather have it there while testing? where can i find it at all, since i havent found it yet

**Comment by Kaktushose** [comment]
https://jda.wiki/setup/logging/

**Comment by JoshCantCode** [comment]
Alright, I've followed that. I also copied your config from https://github.com/Kaktushose/jda-commands/issues/130, and unfortunately theres no documentation in your wiki that tells me how to enable console logging.

**Comment by Kaktushose** [comment]
Well, everyone is responsible for their own logging implementation and setting up logging has nothing to do with my Framework, so no need to mention it in my docs. 
However, I don't know what you mean by console logging. If you followed the JDA guide, you should have a console output

**Comment by JoshCantCode** [comment]
No, for some reason I don't. I still get the same warning as usual in console when the bot starts.

**Comment by JoshCantCode** [comment]
> Well, everyone is responsible for their own logging implementation and setting up logging has nothing to do with my Framework, so no need to mention it in my docs. However, I don't know what you mean by console logging. If you followed the JDA guide, you should have a console output

Also for this, I was mainly wondering where the "logs" mentioned in the built-in error handler embed, and if I'm able to disable it or edit it at all. If not, might be a good feature to add

**Comment by Kaktushose** [comment]
Well, it depends on your logging setup where your log files are stored. If you need further help you need to share your logging configuration in order for me to help you

**Comment by Kaktushose** [comment]
closed due to inactivity
