### ISSUE TITLE
[FEATURE] Guild Scope Commands

### ISSUE THREAD

**Issue by stijnb1234** [Kaktushose/jda-commands#138]
How can I limit a command to a Guild using the scopes feature?

**Comment by Kaktushose** [comment]
Currently, this is not possible. I've never worked with guild scopes. Do you have any ideas for a suitable API design?

**Comment by stijnb1234** [comment]
What does `scope = SlashCommand.CommandScope.GUILD` and `cmds.getImplementationRegistry().setGuildScopeProvider(commandData -> {});` currently do then?

**Comment by Kaktushose** [comment]
😬 Haven't touched this project in a while, so I've actually forgotten about that...

Setting the scope of a SlashCommand to `SlashCommand.CommandScope.GUILD` will, in fact, limit the command for guild usage. You'll then need to provide an implementation of `GuildScopeProvider`. [Javadoc](https://kaktushose.github.io/jda-commands/com/github/kaktushose/jda/commands/scope/DefaultGuildScopeProvider.html#getGuildsForCommand(net.dv8tion.jda.api.interactions.commands.build.CommandData))

```java
@Implementation
public class GuildScopeProviderImpl implements GuildScopeProvider {

    @Override
    public Set<Long> getGuildsForCommand(CommandData commandData) {
        return Set.of(01234567890L); // static result as an example, this would also be the place to perform a database lookup
    }
}
```
