### ISSUE TITLE
Help registering commands.

### ISSUE THREAD

**Issue by aqali1** [Kaktushose/jda-commands#14]
Command Class: https://pastebin.com/JdDrNG2G
Bot Start Method: https://pastebin.com/bjT8RBa7
Help Command Image: https://gyazo.com/ab43de85f3a2542869db7314a8abb967

I have a few commands made but none of them get registered for some reason, using 1.1.0

**Comment by Kaktushose** [comment]
Hello, first of all thanks for using my lib and reporting that bug. That's very strange, I'll look after it asap. Could you also provide a log with DEBUG level?

**Comment by aqali1** [comment]
Noticed I was still on JDA 4.1.1 version, updated it to 4.2.0_191 but it didn't fix.
How would I provide a log like that? Thanks

**Comment by aqali1** [comment]
Nevermind, found MC's debug.log and I was missing some dependancies. Works fine now, thanks!
