### ISSUE TITLE
[BUG] Guild Scope Commands not working

### ISSUE THREAD

**Issue by stijnb1234** [Kaktushose/jda-commands#145]
Related to #138 

Guild scope commands do not work as provided, because the update function is called before the scope can be set.

Like this it works:
```java
JDACommands jdaCommands = JDACommands.start(jda, MyClass.class, "nl.sbdeveloper.mybot.commands");
jdaCommands.getImplementationRegistry().setGuildScopeProvider(commandData -> Set.of(111111111111111111L));
SlashCommandUpdater updater = new SlashCommandUpdater(jdaCommands);
updater.updateGuildCommands();
```

But that's not how it should be.

**Comment by Kaktushose** [comment]
What version of jda-commands are you using?

**Comment by stijnb1234** [comment]
https://github.com/Kaktushose/jda-commands/commit/fce1488337

**Comment by Kaktushose** [comment]
For the moment stick to your solution or use the [`@Implementation`](https://kaktushose.github.io/jda-commands/com/github/kaktushose/jda/commands/annotations/Implementation.html) annotation. I believe this should work. 

Sitenode: @Goldmensch and I are currently working on a new beta release, refactoring most parts of the framework. You can track the process here: https://github.com/users/Kaktushose/projects/1/views/3

**Comment by stijnb1234** [comment]
> For the moment stick to your solution or use the [`@Implementation`](https://kaktushose.github.io/jda-commands/com/github/kaktushose/jda/commands/annotations/Implementation.html) annotation. I believe this should work.
> 
> Sitenode: @Goldmensch and I are currently working on a new beta release, refactoring most parts of the framework. You can track the process here: https://github.com/users/Kaktushose/projects/1/views/3

Cool! It's a private dashboard I think though :P

**Comment by Kaktushose** [comment]
thanks, should be public now
