### ISSUE TITLE
Reflection attempts on obfuscated classes

### ISSUE THREAD

**Issue by aqali1** [Kaktushose/jda-commands#15]
I'm using this as a libary for my Minecraft Sponge plugin which is mixed with JDA, it seems to work fine with the framework and latest reflection shaded, however there are errors on startup from what I believe is other classes being scanned that aren't my plugin. If this is the case, it would be nice to specify a package name used for the command annotation scanning or something else.

https://gist.github.com/Blve151/f514d0c72210642014c22d184986fd52

**Comment by Kaktushose** [comment]
which version of reflection are you using?

**Comment by aqali1** [comment]
I think the above is 0.9.12, but this is 0.9.10
https://pastebin.com/pGRRzrXA

**Comment by Kaktushose** [comment]
I used to have this bug with 0.9.12, but it worked with 0.9.10 for me. So make sure that no other dependency is providing a newer version of reflections. However, I'll also add an option to specify a package
