### ISSUE TITLE
Multiple prefixes 

### ISSUE THREAD

**Issue by aless2003** [Kaktushose/jda-commands#16]
Hey, I didn't find an option for multiple prefixes in the Framework (correct me if I'm wrong). This would be useful for Prefixes which should be independent of the Case (example: miku and Miku) or where a name gets shortened (m! instead of Miku)

**Comment by Kaktushose** [comment]
thats not possible yet, will be implemented in 1.1.1

**Comment by aless2003** [comment]
Alright, thanks for the Info :)

**Comment by Kaktushose** [comment]
implemented :) hmu if you have any further questions
