### ISSUE TITLE
Class Categories

### ISSUE THREAD

**Issue by aless2003** [Kaktushose/jda-commands#17]
Hello, is there a way to set the category of all commands in a, as a CommandController annotated, Class once?

For example, if I had something like this: 
```
@CommandController
public class SecurityCommands {

@Command(value = "aCommand", category = "Security")
public void aCommand(CommandEvent event) {...}

@Command(value = "AnotherCommand", category "Security)
public void anotherCommand(CommandEvent event) {...}
}
```

would it be possible to set the category once for all the Commands instead of applying the category on each Command individually?

**Comment by Kaktushose** [comment]
will be implemented
