### ISSUE TITLE
Comand settings

### ISSUE THREAD

**Issue by OisinHick** [Kaktushose/jda-commands#20]
None of the command settings class appears to be working for me making me unable to set command permissions etc.
Cannot make a static reference to the non-static method getPermissionHolders(String) from the type CommandSettings

**Comment by Kaktushose** [comment]
Could you please provide your code?

**Comment by OisinHick** [comment]
`        //setsup the programs main class
	 public static void main(String[] args) throws LoginException, InterruptedException {
		 
		    	        
		// Creates new Jda object called cyman with the key to link it to discord
	        JDA cyman = JDABuilder.createDefault("Discord Token")
	        		
	        					//adds event listener for messages
	        					.addEventListeners(new Cyman())
	        					
	        					//builds the jda object
	        					.build();

			// optionally block until JDA is ready
	        cyman.awaitReady();
			
	        
	        //makes the command builder object
	       JDACommandsBuilder.start(cyman,
	                 "#",  // prefix
	                 true, // ignore bots
	                 true, // ignore label case
	                 true);// use bot mention as prefix
	       
	    CommandSettings.getPermissionHolders("Admin_Permissions");
	      
	    }`

I've tried a few different things but no matter what I can't seem to get this to work properly. Am I doing something wrong?

**Comment by OisinHick** [comment]
` //setsup the programs main class
	 public static void main(String[] args) throws LoginException, InterruptedException {
		 
		    	        
		    // Creates new Jda object called cyman with the key to link it to discord
	        JDA cyman = JDABuilder.createDefault("discord token here")
	        		
	        					//adds event listener for messages
	        					.addEventListeners(new Cyman())
	        					
	        					//builds the jda object
	        					.build();

			// optionally block until JDA is ready
	        cyman.awaitReady();
			
	        /*
	        
	        //makes the command builder object
	       JDACommandsBuilder.start(cyman,
	                 "#",  // prefix
	                 true, // ignore bots
	                 true, // ignore label case
	                 true);// use bot mention as prefix
	       
	    */
	        
	        commandSettings.setPrefix("!")
	        .setIgnoreBots(true)
	        .setIgnoreLabelCase(true)
	        .setBotMentionPrefix(true);
	       

        	jdaCommands = jdaCommandsBuilder.setDefaultSettings(commandSettings).build();
	      
	    }`

this doesn't seem to work either

**Comment by Kaktushose** [comment]
`CommandSettings.getPermissionHolders("Admin_Permissions");` doesn't work, because `getPermissionHolders` isn't a static method, but you try to access it in a static context.

Your second approach is also wrong, because you first build JDACommands via `JDACommandsBuilder#start()` and then a second time via `JDACommandsBuilder#build()`. 

Let me show you one possible way how to do it correctly:
```java
// create jda object
JDA jda = yourJDABuilding();

// create JDACommandsBuilder object
JDACommandsBuilder jdaCommandsBuilder = new JDACommandsBuilder(jda);

// create a new CommandSettings object
// of course you can change the boolean values to whatever you want
CommandSettings commandSettings = new CommandSettings("yourPrefix", true, true, true);

// get the Set of permission holders for Admin_Permissions and add a user to it
commandSettings.getPermissionHolders("Admin_Permissions").add(123456789L); 

// set the CommandSettings to the builder
jdaCommandsBuilder.setDefaultSettings(commandSettings);

// build and start jdaCommands
JDACommands jdaCommands = jdaCommandsBuilder.build();
```

Also you should have a look at the wiki for [CommandSettings](https://github.com/Kaktushose/jda-commands/wiki/CommandSettings) and [Permissions](https://github.com/Kaktushose/jda-commands/wiki/Permissions) or the JavaDoc for the [JDACommandsBuilder](https://kaktushose.github.io/jda-commands/com/github/kaktushose/jda/commands/entities/JDACommandsBuilder.html)

**Comment by OisinHick** [comment]
thank you i could not for the life of me figure out how to do it. I did consult the docs but I clearly didn't interpret it right. do I run all this in a separate class?

**Comment by Kaktushose** [comment]
you can run it wherever you want

**Comment by OisinHick** [comment]
Brilliant thank you for your help. hopefully this will help someone else
