### ISSUE TITLE
Show users the name of the argument that is missing

### ISSUE THREAD

**Issue by MeerBiene** [Kaktushose/jda-commands#21]
![](https://i.imgur.com/iW8LSxA.png)

**Code:**

```java
@Command("reactionmsg")
    public void onTellAge(CommandEvent event, int age) {
        event.reply(String.format("You are %s years old.", age));
    }
```

**Expected Behavior**

Tells the user that the missing argument was "age" of type "INTEGER"

**Comment by Kaktushose** [comment]
For some reason it is not possible to get the parameter name via Reflections. Nonetheless, I have added "human readable" type names to the EmbedFactory, e.g. `INTEGER` -> `Number`
