### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by aless2003** [Kaktushose/jda-commands#22]
Hey, wanted to ask if there is any sort of Plugin Support for this Framework, as it would be quite useful.

**Comment by Kaktushose** [comment]
Could you please specify what you mean? In terms of manipulating the framwork's behaviour have a look at the [wiki](https://github.com/Kaktushose/jda-commands/wiki/Advanced-Configuration)

**Comment by aless2003** [comment]
I mean like something where you can give the Framework a Path on which it should check for .jar files and checks those for Commands too. Like for extending the Bot after it was initially deployed. Would give it some more modularity for Bots where you only want specific Modules to run for example.

**Comment by Kaktushose** [comment]
ah okay. I've already thought about sth like this and tried to implement it with serialization (https://github.com/Kaktushose/jda-commands/tree/feature/store-commands) but it didn't work. I really like the idea and will think about it

**Comment by aless2003** [comment]
Oh alright, thanks for considering it then 👍

**Comment by Kaktushose** [comment]
Update: 

This will be worked on, as it goes hand in hand with some other features I have in mind. 

See the [project board](https://github.com/Kaktushose/jda-commands/projects/3#card-68300932) for details

**Comment by aless2003** [comment]
I'm currently experimenting a little with pf4j to see if this would be a viable option, if it is I'll make a simple implementation

**Comment by aless2003** [comment]
Alright so my experiments seem to have been successful. A very simple implementation can be found here: https://github.com/aless2003/jda-commands/tree/plugin_support 
Also an example plugin can be found here:
https://github.com/aless2003/SimpleJDAPluginExample

Basically what it does is to load the Jar with all the commands via the pf4j library. Plugins must extend the `com.github.Kaktushose.jda.commands.plugins.CommandPlugin` Interface. All plugins are then saved in a list and will then be checked for the CommandController annotation. From there it's going back to the same algorithm as the current implementation. If somebody wants to give me some feedback whether this looks like a valid approach I'll go make it pull request ready and create one to discuss about needed changes.

**Comment by Kaktushose** [comment]
Thanks for your work. The implementation looks good so far. However, from my understanding, we don't need pf4j and could easily implement our own plugin system

**Comment by aless2003** [comment]
That was my first try, the issue comes when loading classes dynamically. I tried to make a simple ClassLoader implementation for it, but whenever I tried to load anything, it wouldn't load it correctly or had issues with annotations. pf4j already has that implemented as well as some libraries to give it additional functionality if we ever need it. However, if you want, I can take another shot at making our own Plugin System

**Comment by aless2003** [comment]
Alright, took me a while but my current implementation works based on the URLClassLoader from basic Java as well as the JarFile class. That way it does not rely on any outside Classes and should not modify the current pom.xml anymore.
Anything else I should be aware of?

**Comment by Kaktushose** [comment]
sorry that i left this here but the development kinda came to a halt for a few months. I've worked on a new version so this would need lots of refactoring, also I must admit that I don't see the use case such feature anymore. Back then you've mentionend 
> modularity for Bots where you only want specific Modules to run for example.
but i think that you can achieve this by using Filters, GuildScopes or even messing around with the jda-commands object itself. So I'd see this as a wontfix atm
