### ISSUE TITLE
Private Messages Support

### ISSUE THREAD

**Issue by aless2003** [Kaktushose/jda-commands#28]
As only `onGuildMessageReceived` events are getting used by the Command Framework I wondered if there was a way to enable private Messages for certain Commands, without having to write a whole own `CommandDispatcher` and by extension a whole own `JDACommandsBuilder` class. It would be quite nice for, as an example, authentication of a user for a third-party service.

**Comment by Kaktushose** [comment]
I already thought about this but wasn't sure how to handle the whole guild settings stuff. But I'll look into it
