### ISSUE TITLE
A way to disable Command Not Found Embed

### ISSUE THREAD

**Issue by aless2003** [Kaktushose/jda-commands#33]
It would be great if I somehow could disable this behaviour, as it sometimes appears in a conversation.
As how it is currently, I would need to write a completely own CommandDispatcher and since this is a final class, which is needed by JDACommands and JDACommandsBuilder, I would need to make new Versions of both of these classes, just to disable the CommandNotFound embeds from sending.

**Comment by Kaktushose** [comment]
Good catch. I'm currently working on version 2.0 (see #32) so don't put too much effort in a workaround ;)

**Comment by Kaktushose** [comment]
This got actually introduced with #27

**Comment by aless2003** [comment]
Ah sorry, my bad 😅

**Comment by Kaktushose** [comment]
forgot about it as well (tbh I should've released another version before starting the rewrite, but anyway)
