### ISSUE TITLE
Resolving User/Member from parameters not working due to usage of getUserById / getMemberById

### ISSUE THREAD

**Issue by stijnb1234** [Kaktushose/jda-commands#36]
Currently you are using getUserById / getMemberById to resolve the users / members. But if the cache is empty, this will always return null.

You should use retrieveUserById / retrieveMemberById to fix these issues. This will load into cache and return the correct object.

https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDA.html#retrieveUserById(java.lang.String)
https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.html#retrieveMemberById(java.lang.String)

**Comment by Kaktushose** [comment]
Thanks for pointing out, this will be resolved in #32
