### ISSUE TITLE
[FEATURE] Enum parsing

### ISSUE THREAD

**Issue by stijnb1234** [Kaktushose/jda-commands#47]
It would be great if it was possible to parse enums. ;)

**Comment by Kaktushose** [comment]
This would be hard to implement as a default adapter, because jda-commands would need to know about all enums inside the classpath. Thus, I'll probably not implement this. However, you can implement your own adapter pretty easily. See the [wiki](https://github.com/Kaktushose/jda-commands/wiki/Type-Adapter) or the [javadoc](https://kaktushose.github.io/jda-commands/com/github/kaktushose/jda/commands/dispatching/adapter/package-summary.html) for details

**Comment by stijnb1234** [comment]
> This would be hard to implement as a default adapter, because jda-commands would need to know about all enums inside the classpath. Thus, I'll probably not implement this. However, you can implement your own adapter pretty easily. See the [wiki](https://github.com/Kaktushose/jda-commands/wiki/Type-Adapter) or the [javadoc](https://kaktushose.github.io/jda-commands/com/github/kaktushose/jda/commands/dispatching/adapter/package-summary.html) for details

Maybe something like a shortcut methode for implementing an enum?
```
jdaCommands.getAdapterRegistry().registerEnum(MyEnum.class);
```

The problem I have myself with the implementation is that there is no way to check the given parameter type for the argument that is being parsed.

**Comment by Kaktushose** [comment]
this is actually a bug / misconception I diddn't notice before. Since the adapter registering takes places after command indexing, it's basically impossible to use own adapters. Will think about a solution asap

**Comment by Kaktushose** [comment]
Version 2.2.0 just released an fixed this issue. If a command has a parameter with no type adapter present, the command will still get registered and a warn message is displayed. I decided against native enum support but writing your own type adapter became fairly easy:

```java
@Component
public class MyEnumAdapter implements TypeAdapter<MyEnum> {

    @Override
    public Optional<MyEnum> parse(@NotNull String raw, @NotNull CommandContext context) {
        return Optional.of(MyEnum.valueOf(raw));
    }
}
```

When using the Component annoation the adapter will be present even before command indexing. But it'll also work if you use the jdaCommands object:

```java
jdaCommands.getAdapterRegistry().register(MyEnum.class, new MyEnumAdapter());
```

**Comment by stijnb1234** [comment]
> Version 2.2.0 just released an fixed this issue. If a command has a parameter with no type adapter present, the command will still get registered and a warn message is displayed. I decided against native enum support but writing your own type adapter became fairly easy:
> 
> ```java
> @Component
> public class MyEnumAdapter implements TypeAdapter<MyEnum> {
> 
>     @Override
>     public Optional<MyEnum> parse(@NotNull String raw, @NotNull CommandContext context) {
>         return Optional.of(MyEnum.valueOf(raw));
>     }
> }
> ```
> 
> When using the Component annoation the adapter will be present even before command indexing. But it'll also work if you use the jdaCommands object:
> 
> ```java
> jdaCommands.getAdapterRegistry().register(MyEnum.class, new MyEnumAdapter());
> ```

That's perfect. Thanks for your inplementation. 👍
