### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by jordanamr** [Kaktushose/jda-commands#5]
Hello, is there any way you could add i18n to the error/info messages that are hardcoded into the lib? For example having a different language per server the same way prefixes work.
Thank you :)

**Comment by Kaktushose** [comment]
i18n is something I've actually been planning to do, but so far I didn't find time to implement it. I hopefully get managed to add it to the next release. For the moment you can already change the embeds, and thus the language, by modifying the embed factory. https://github.com/Kaktushose/jda-commands/wiki/Advanced-Configuration

**Comment by jordanamr** [comment]
Lovely, I'll look into it, get my star sir

**Comment by Kaktushose** [comment]
i18n is now implemented. I'll write the wiki for it within the next days.  let me know if you have any questions :)
