### ISSUE TITLE
No choice support?

### ISSUE THREAD

**Issue by Verdanix** [Kaktushose/jda-commands#57]
Hello,
I love this API so far, it has great features, but my question is that I don't quite see any choice support for commands. If I am incorrect I would like to know please as I am kinda oblivious sometimes. 

If(ChoiceSupport == null){
tellMe();
possiblyAddChoiceSupport();
thanks();
}

**Comment by Kaktushose** [comment]
Hello,

similar to #31 I'll put this on freeze until JDA5 hits at least beta status or the interaction api is stable enough to start working with it. 

I'd also love to integrate the new interaction types into my bot, but writing de facto legacy code (with JDA4) just doesn't make sense.

**Comment by Kaktushose** [comment]
Update:

I've started working on interactions. See [dev-jda5](https://github.com/Kaktushose/jda-commands/tree/dev-jda5) and the [project board](https://github.com/Kaktushose/jda-commands/projects/4) for details.

**Comment by Kaktushose** [comment]
Update:

This feature is now available in [`v2.3.0-alpha.1`](https://github.com/Kaktushose/jda-commands/releases/tag/v2.3.0-alpha.1)
