### ISSUE TITLE
Question about jdav5 version

### ISSUE THREAD

**Issue by prevaure** [Kaktushose/jda-commands#63]
Hi !

I've seen you're currently working on a major update supporting interactions.
Do you have a release date for now ? Or is it already functionnal, so we can build it ourselves ?

Thanks for your incredible work and have a nice day

**Comment by Kaktushose** [comment]
Hey there.

No, there is no ETA and I won't be more specific than soon:tm: because I am very bad at meeting deadlines 🙈 

But what I can tell you is that I've already implemented slash commands. You can use the [`latest commit`](https://github.com/Kaktushose/jda-commands/commit/5a210f3ee11ff75b49dc8e48309e537abce895d9) which however comes with no proper docs (besides Javadoc) and probably has some bugs. 

Currently I'm working on implementing buttons, which will also become available soon.

Quick start for slash commands: 

```java
JDACommands.slash(jda, Main.class).startGlobal();
```

or to use guild scope:

```java
JDACommands.slash(jda, Main.class).guilds(0123456789L).startGuild();
```

That's it. You don't need to change your command classes, the new version provides backwards compatibility.

**Comment by prevaure** [comment]
Okay thanks !!

The bot booted up correctly by specifying the registrationPolicy.
Are all commands created as slash commands automatically ?

**Comment by Kaktushose** [comment]
> The bot booted up correctly by specifying the registrationPolicy

whoops, haven't pushed my recent changes on that one.


> Are all commands created as slash commands automatically ?

yes

**Comment by prevaure** [comment]
Uh I may have made a mistake then, bc none of my command is showing up in
the slash menu, even if I call the SlashCommandUpdater and ask for the
update() method

Le lun. 13 juin 2022 à 22:24, Kaktushose ***@***.***> a
écrit :

**Comment by Kaktushose** [comment]
are you using global or guild scope? because global commands may need up to one hour to show up

**Comment by prevaure** [comment]
I tried both of them, with regPolicy set on TEXT_AND_SLASH and SLASH. I couldn't figure out what MIGRATING was (maybe i should have set it up ?)

**Comment by Kaktushose** [comment]
```java
    /**
     * This policy will register slash commands and will respond with a deprecation message to text commands.
     */
    MIGRATING
```

Please send me full debug log so I can look into this issue further

**Comment by prevaure** [comment]
Yep I'll send it tomorrow morning, I don't have my computer rn

**Comment by prevaure** [comment]
Hi mate,

Here are attached the logs in pdf. First with the MIGRATING policy, then with TEXT_AND_SLASH, and by specifying a guild, slash commands don't show up, neither they work. When using TEXT_AND_SLASH, commands work with prefix but not with slash.

Here's my code :

`JDACommands jdaCommands = JDACommands.slash(api, Bot.class).registrationPolicy(CommandRegistrationPolicy.MIGRATING).guilds(871805279568797797L).startGuild();`
[logs.pdf](https://github.com/Kaktushose/jda-commands/files/8898771/logs.pdf)

**Comment by Kaktushose** [comment]
Can you show me your jda building as well?

**Comment by prevaure** [comment]
Yup,

https://www.toptal.com/developers/hastebin/rojekibide.lua

Also the class where I build jda and jda commands is not the main class, I call it from the main() method in another class.

**Comment by Kaktushose** [comment]
Make sure to use `awaitReady()`. This will block until JDA is ready. Atm jda-commands connot upsert commands because JDA isnt ready

**Comment by prevaure** [comment]
Okay thanks it worked ! I have three issues :
1) Commands are registered two times in the slash command menu [https://i.imgur.com/RO596cV.png](https://i.imgur.com/RO596cV.png)

2) When running a command I get an exception : https://www.toptal.com/developers/hastebin/agutowuxex.sql

3) When we run the /help command, the bot answers, but discord says "the app doesn't answer" as ephemeral reply (and help is sent as regular message) : https://i.imgur.com/2xSTu2B.png maybe discord wants the app to answer with ephemeral answer only ?

**Comment by Kaktushose** [comment]
1. Probably a client issue. Technically a slash command cannot be registered twice

2. Can you show me the command code?

3. Will look into it when I am back at my PC

**Comment by prevaure** [comment]
I figured the solution for the 1 :
The commands had been registered twice by the bot as global and as guild. Which means that ebery command was available in those two "versions" if i can say so. What I did to fix it is that I set regPolicy to TEXT and the scope to guild, so SlashCommandUpdater unregisters guild slash commands. Now, I have set regPolicy to TEXT_AND_SLASH and global scope and the commands are not duplicated anymore.

2. Yes https://www.toptal.com/developers/hastebin/imofeqeduv.cpp the command works when calling it with the prefix, but not with the slash command. ephemeral boolean's value doesn't change anything, I tried both true and false

**Comment by Kaktushose** [comment]
1. Ah okay, I might add a clearCommands method to make this easier

2. Library error, will fix it soon

**Comment by prevaure** [comment]
Okay thanks !

For the 2 I'll try to figure out another solution as I get to access to ephemeral replies now.

About the help message, it appears the library is not handling the "/help" command as a slash command and is not answering to it properly, I'll try to look further into it

**Comment by Kaktushose** [comment]
Guickfix would be to not use callbacks in your command class

**Comment by prevaure** [comment]
Okay, got a fix for the help command. 

https://github.com/prevaure/jda-commands-elybot/commit/f00b7afdfe2f8e434bc34d8a605308ae33a8c6ee
Just added that on my fork. Trashy way, but it works

**Comment by prevaure** [comment]
Re, I found another bug : 
When using super and sub commands with slash, only the subcommand will be registered and usable with slash.
I tried both usage cases you describe in the wiki, and only the subcommand was ok
The command tree was okay though

**Comment by Kaktushose** [comment]
Not a bug, its related to didcords limitations. When you have a command `/foo bar` you cannot have a command `/foo`

**Comment by prevaure** [comment]
Okay I see, will go for args

Also, to add our own constraints, nothing has changed from https://github.com/Kaktushose/jda-commands/wiki/Own-Constraints ?
I can see in the debug that the validator is well registered but the command passes the constraint everytime even if it should not, so no error is thrown

**Comment by Kaktushose** [comment]
Okay, so that's a nasty bug. 
The problem was that when using `#getValidatorRegistry().register()` command indexing already took place, so essentially its too late to register new validators. 

So, the wiki was simply wrong, I've updated it with the correct solution

**Comment by Kaktushose** [comment]
> Okay, got a fix for the help command.
> 
> [prevaure@f00b7af](https://github.com/prevaure/jda-commands-elybot/commit/f00b7afdfe2f8e434bc34d8a605308ae33a8c6ee) Just added that on my fork. Trashy way, but it works

looks fine, feel free to open a pr

**Comment by Kaktushose** [comment]
> 2. When running a command I get an exception : https://www.toptal.com/developers/hastebin/agutowuxex.sql

fixed with 23affa94c7addb9bd6bfcda1ebff0fc9f8cf4220

**Comment by prevaure** [comment]
> Okay, so that's a nasty bug. The problem was that when using `#getValidatorRegistry().register()` command indexing already took place, so essentially its too late to register new validators.
> 
> So, the wiki was simply wrong, I've updated it with the correct solution

Okay thanks

**Comment by prevaure** [comment]
> > Okay, got a fix for the help command.
> > [prevaure@f00b7af](https://github.com/prevaure/jda-commands-elybot/commit/f00b7afdfe2f8e434bc34d8a605308ae33a8c6ee) Just added that on my fork. Trashy way, but it works
> 
> looks fine, feel free to open a pr

I can't as I modified too many things on my fork.
Is your recent push with all the commits stable ? I will use it instead of my commit then

**Comment by Kaktushose** [comment]
as stable as a dev branch is

**Comment by prevaure** [comment]
Okay thx
Nothing changes if I just maj the maven dependency ? About the method
usage, etc

Le mer. 15 juin 2022 à 09:41, Kaktushose ***@***.***> a
écrit :

**Comment by Kaktushose** [comment]
Nothing prior to 2.3.0 changes, in development code might have changed. What method usage do you mean?

**Comment by prevaure** [comment]
I mean if I update with the new dev-jda5 branch, will i need to change
anything if I used the dev-jda5 from the ephemeral replies commit ?

Le mer. 15 juin 2022 à 13:09, Kaktushose ***@***.***> a
écrit :

**Comment by Kaktushose** [comment]
depends on what code you've used... 
[here you can find the changelog](https://github.com/Kaktushose/jda-commands/compare/5a210f3..23affa9)

**Comment by prevaure** [comment]
Hi again,

I had a question about the permission system. In the wiki, it's written that we can create our own permission system (but by default the supported one is the discord one). Could you explain how to customize it ? For example, if i want to create a ban command available to ppl with my own ban_members permission but not the discord one ?

Ofc I could do the check right into the code and see what role they have or some stuff like that but i was wondering if there's a way to do so with the @Permission annotation

**Comment by Kaktushose** [comment]
```java
@Component
public class MyPermissionsProvider implements PermissionsProvider {

    @Override
    public boolean isMuted(@NotNull User user, @NotNull CommandContext context) {
       
    }

    @Override
    public boolean hasPermission(@NotNull User user, @NotNull CommandContext context) {
    }

    @Override
    public boolean hasPermission(@NotNull Member member, @NotNull CommandContext context) {
    }

}
```

will do the job
