### ISSUE TITLE
Issue pulling dependency

### ISSUE THREAD

**Issue by aless2003** [Kaktushose/jda-commands#66]
Hey, I wanted to push a fix for my bot yesterday, but my CI/CD pipeline couldn't compile it because it couldn't resolve "com.github.Kaktushose:jda-commands:v.2.2.0". Naturally I thought I accidentally changed that line and copy pasted the line from the release in it again, but it seems like it is not usable. Was there any change in naming I'm not aware of?

**Comment by prevaure** [comment]
Hi, did you added the jitpack repository ?

**Comment by aless2003** [comment]
I did. I can download version 1.1.1 for example, but not v.2.2.0

**Comment by Kaktushose** [comment]
Works on my machine. Maybe try the latest commit on master as a work around

**Comment by aless2003** [comment]
Will do. Did you clear your local gradle/maven cache before trying though? Cause it worked for me locally because of that, but as soon as I cleared that it didn't work anymore

**Comment by Kaktushose** [comment]
nah, I didn't clear cache

**Comment by aless2003** [comment]
Maybe you can reproduce it if you do that, just a guess though

**Comment by stijnb1234** [comment]
Works fine for me.

**Comment by aless2003** [comment]
Retried it again just now and it worked, maybe just a temporary issue, I'll close this issue
