### ISSUE TITLE
Button Questions

### ISSUE THREAD

**Issue by aless2003** [Kaktushose/jda-commands#75]
So I'm in the process of preparing my Bot for JDA 5. So naturally I'm also updating the jda-commands version to 2.3.0-alpha.2. And while I've gotten most things to work I have a few Questions about the JDA-Commands Buttons.

1. Is there a way to just have a label?
    As it stands right now, it just gets replaced by "empty label", but in some cases I simply don't want a label to be present (e.g. Music Player Controls)
2. Why can't I set the Emoji for Buttons as literal Emojis (e.g. ⏩instead of U+23E9), because as far as the Emoji Interface from JDA goes, it should be possible according to the JavaDocs.

3. This one is just out of curiosity, but the Button Annotation's JavaDocs say something about "retruns an Optional hold the x", even though none of the methods return an Optional

**Comment by Kaktushose** [comment]
1. Wasn't aware this was possible, removed it

2. simplified it, now `Emoji#fromFormatted` just gets called

3. copy & paste error, fixed it
