### ISSUE TITLE
Not finding commands in jar

### ISSUE THREAD

**Issue by aless2003** [Kaktushose/jda-commands#81]
So, as I'm preparing my bot for JDA 5 and 2.3.0 of JDA-Commands, I have noticed that my current CI/CD breaks when packaging the bot in a jar file (runs normally when not running it as a jar file). It breaks in form of not finding any Commands anymore. In Version 2.2.0 this wasn't an issue and worked flawlessly. 

Here's the code with which I start my Bot:
```
String[] packages = {"main.discord.commands", "main.api.jdaCommands"};
JDACommands commands = JDACommands.start(manager, Main.class, packages);
```

I've also included my debug level log file as well as my info level log file in case you need it. (Bot related stuff should start after "Starting JDA-Commands")

[debug.log](https://github.com/Kaktushose/jda-commands/files/9277621/debug.log)
[info.log](https://github.com/Kaktushose/jda-commands/files/9277622/info.log)

**Comment by Kaktushose** [comment]
Does the probem still exist?

**Comment by aless2003** [comment]
Just tested with the newest commit of branch dev-jda5. Seems to still be the case. Reflections keeps responding with "producing 0 keys and 0 values"

**Comment by Kaktushose** [comment]
we had this issue already in the past, see #18. Interesting to have it back. iirc I've updated reflections recently, so maybe downgrading again will do the trick

**Comment by aless2003** [comment]
I've found this GitHub Issue on the reflections repository: https://github.com/ronmamo/reflections/issues/373
Maybe It'll help

**Comment by Kaktushose** [comment]
Thanks. I'll try to reproduce the bug and then try to apply the workaround and otherwise I should consider to pick [this project](https://github.com/Kaktushose/mirror) up again

**Comment by Kaktushose** [comment]
Or maybe we should move away from using runtime reflections at all

**Comment by Kaktushose** [comment]
Version [4.0.0-alpha.1](https://github.com/Kaktushose/jda-commands/releases/tag/v4.0.0-alpha.1) implements the fix found https://github.com/ronmamo/reflections/issues/373. If this error persists feel to open a new issue
