### ISSUE TITLE
[FEATURE] Set default permissions for commands

### ISSUE THREAD

**Issue by HappyAreaBean** [Kaktushose/jda-commands#85]
Will there be a way to let us set the default permission? [(Managing Slash Command Permissions)](https://jda.wiki/using-jda/interactions/#managing-slash-command-permissions)
It would be helpful to limit certain commands access only to the admin or a specific role.

**Comment by Kaktushose** [comment]
Since it's now up to admins to set up the perms and the old permission system ist still up and running, this isn't a priority to add for me, but I'll certainly implement the new permission system in the near future

**Comment by Kaktushose** [comment]
added with [4.0.0-alpha.1](https://github.com/Kaktushose/jda-commands/releases/tag/v4.0.0-alpha.1)
