### ISSUE TITLE
[BUG] Member parser does not work in other channels then default text

### ISSUE THREAD

**Issue by stijnb1234** [Kaktushose/jda-commands#93]
The member parser does not parse the member when I use a slash command in for example an announcement channel.

![image](https://user-images.githubusercontent.com/27051051/193658235-41890c25-87f9-43cc-bc21-88ec0ae64f79.png)

In normal text channels it works fine.

My code:
```Java
@CommandController
public class Warn {
    @Command(value = "warn", desc = "Warn a member.")
    @Permission("{KICK_MEMBERS}")
    public void onWarn(CommandEvent event, @Param(name = "member", value = "The member to warn") Member user, @Optional("None") @Param(name = "reason", value = "The reason to warn the member") String reason) {
    }
}
```

**Comment by Kaktushose** [comment]
as for version 3 (respectively version 2) this must be seen as a wontfix. However feel free to migrate to version 4 and start using interactions
